/**
 * codegen.ts
 *
 * Walks a validated Mava DSL AST and generates JavaScript glue code.
 * Output is a self-contained JS string that:
 *   - Registers trigger handlers into the project event system
 *   - Uses elementStore, varStore, pagesStore via injected context
 *   - Dispatches execute actions through the action registry
 *   - Wires variable.change watchers via Vue's watch()
 *
 * The generated code is NOT an ES module — it runs inside a
 * Function() scope with context injected, same as user scripts.
 *
 * Injected context shape:
 *   __el(id)        — get element proxy by id
 *   __var           — variable store proxy (project proxy)
 *   __page          — pagesStore
 *   __dispatch      — dispatchActions(actions, context)
 *   __watch(fn, cb) — Vue watch wrapper
 *   __on(event, target, handler) — register event listener on element
 *   __off(event, target, handler) — remove event listener
 *   __navigate(id)  — navigate to page
 *   __lock(id)      — lock page/section
 *   __unlock(id)    — unlock page/section
 *   __waitMs(ms)    — returns Promise that resolves after ms
 */

import type {
    ProgramNode, DefinitionNode,
    GroupDefNode, NamedTriggerDefNode, TriggerDefNode,
    TriggerBodyNode, EventClauseNode, EventSpecNode,
    SubjectNode, ConditionalBodyNode, ShortBodyNode,
    WhenBranchNode, ElseBranchNode,
    ExprNode, BinaryExprNode, UnaryExprNode,
    ComparisonNode, IdentifierNode, LiteralNode,
    ActionNode, TargetedActionNode,
    NavigateActionNode, WaitActionNode,
    ExecuteActionNode, TriggerActionNode,
    AssignActionNode,
} from './ast'

// ─── Output ───────────────────────────────────────────────────────────────────

export interface CodeGenResult {
    code: string
    // Named trigger function names — for external invocation
    namedTriggers: Record<string, string>
}

// ─── Indentation helper ───────────────────────────────────────────────────────

class CodeWriter {
    private lines: string[] = []
    private indent: number = 0

    push(line: string = '') {
        this.lines.push(line
            ? `${'  '.repeat(this.indent)}${line}`
            : ''
        )
    }

    in() { this.indent++ }
    out() { this.indent = Math.max(0, this.indent - 1) }

    toString(): string {
        return this.lines.join('\n')
    }
}

// ─── Code generator ───────────────────────────────────────────────────────────

export function codegen(ast: ProgramNode): CodeGenResult {
    const w = new CodeWriter()
    const namedTriggers: Record<string, string> = {}

    // Groups are resolved at parse/validate time — we inline their members
    // directly in the generated code. Build a lookup here.
    const groups: Map<string, { kind: 'element' | 'variable'; members: string[] }> = new Map()

    for (const def of ast.body) {
        if (def.type === 'GroupDef') {
            groups.set(def.name, { kind: def.groupKind, members: def.members })
        }
    }

    // ── Preamble ──────────────────────────────────────────────────────────────

    w.push('// Generated by Mava DSL codegen — do not edit manually')
    w.push(`// Generated at: ${new Date().toISOString()}`)
    w.push()
    w.push('const __cleanups = [];')
    w.push()

    // ── Named trigger functions ────────────────────────────────────────────────

    for (const def of ast.body) {
        if (def.type === 'NamedTriggerDef') {
            const fnName = `__trigger_${sanitizeId(def.name)}`
            namedTriggers[def.name] = fnName
            w.push(`async function ${fnName}() {`)
            w.in()
            genTriggerBody(def.body, w, groups, namedTriggers)
            w.out()
            w.push('}')
            w.push()
        }
    }

    // ── Local triggers ────────────────────────────────────────────────────────

    let triggerIndex = 0
    for (const def of ast.body) {
        if (def.type === 'TriggerDef') {
            triggerIndex++
            w.push(`// Trigger ${triggerIndex}`)
            genTriggerRegistration(def.body, triggerIndex, w, groups, namedTriggers)
            w.push()
        }
    }

    // ── Cleanup export ────────────────────────────────────────────────────────

    w.push('// Return cleanup function to unregister all listeners')
    w.push('return function cleanup() {')
    w.in()
    w.push('__cleanups.forEach(fn => fn());')
    w.out()
    w.push('};')

    return { code: w.toString(), namedTriggers }
}

// ─── Trigger registration ─────────────────────────────────────────────────────

/**
 * Generates the event listener registration for a trigger.
 * For variable.change events, uses __watch.
 * For all others, uses __on with data-eid queries.
 */
function genTriggerRegistration(
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    const clause = body.eventClause

    if (clause.qualifier === 'single' || clause.qualifier === 'either') {
        // Each event independently fires the handler
        for (const event of clause.events) {
            genSingleEventRegistration(event, body, index, w, groups, namedTriggers)
        }
    } else {
        // all-of — all events must fire before handler runs
        genAllOfRegistration(clause, body, index, w, groups, namedTriggers)
    }
}

function genSingleEventRegistration(
    event: EventSpecNode,
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    const handlerName = `__handler_${index}_${sanitizeId(event.name)}`

    w.push(`async function ${handlerName}(event) {`)
    w.in()
    genTriggerBody(body, w, groups, namedTriggers)
    w.out()
    w.push('}')
    w.push()

    // variable.change → Vue watcher
    if (event.name === 'variable.change') {
        const varName = event.subject?.ids[0] ?? ''
        w.push(`{`)
        w.in()
        w.push(`const stop = __watch(`)
        w.in()
        w.push(`() => __var['${varName}'],`)
        w.push(`(newVal, oldVal) => ${handlerName}({ newVal, oldVal })`)
        w.out()
        w.push(');')
        w.push(`__cleanups.push(stop);`)
        w.out()
        w.push(`}`)
        return
    }

    // timeline.* → custom timeline event
    if (event.name.startsWith('timeline.')) {
        genTimelineRegistration(event, handlerName, w)
        return
    }

    // Page lifecycle events
    if (isLifecycleEvent(event.name)) {
        genLifecycleRegistration(event, handlerName, w)
        return
    }

    // DOM events — register on each target element
    const targets = resolveEventTargets(event, groups)
    const domEvent = mapToDomEvent(event.name)

    for (const targetId of targets) {
        w.push(`{`)
        w.in()
        w.push(`const __node = document.querySelector('[data-eid="${targetId}"]');`)
        w.push(`if (__node) {`)
        w.in()
        w.push(`__node.addEventListener('${domEvent}', ${handlerName});`)
        w.push(`__cleanups.push(() => __node.removeEventListener('${domEvent}', ${handlerName}));`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
    }
}

function genAllOfRegistration(
    clause: EventClauseNode,
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    // Track which events have fired using a Set
    // Handler fires only when all events have been seen
    const firedSetName = `__fired_${index}`
    const totalEvents = clause.events.length

    w.push(`const ${firedSetName} = new Set();`)
    w.push()

    for (let i = 0; i < clause.events.length; i++) {
        const event = clause.events[i]
        const handlerName = `__handler_${index}_allof_${i}`

        w.push(`async function ${handlerName}(event) {`)
        w.in()
        w.push(`${firedSetName}.add(${i});`)
        w.push(`if (${firedSetName}.size === ${totalEvents}) {`)
        w.in()
        w.push(`${firedSetName}.clear();`)
        genTriggerBody(body, w, groups, namedTriggers)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
        w.push()

        // Register same as single event
        genSingleEventForAllOf(event, handlerName, groups, w)
    }
}

function genSingleEventForAllOf(
    event: EventSpecNode,
    handler: string,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    w: CodeWriter,
) {
    if (event.name === 'variable.change') {
        const varName = event.subject?.ids[0] ?? ''
        w.push(`{`)
        w.in()
        w.push(`const stop = __watch(() => __var['${varName}'], (nv, ov) => ${handler}({ newVal: nv, oldVal: ov }));`)
        w.push(`__cleanups.push(stop);`)
        w.out()
        w.push(`}`)
        return
    }

    if (isLifecycleEvent(event.name)) {
        genLifecycleRegistration(event, handler, w)
        return
    }

    const targets = resolveEventTargets(event, groups)
    const domEvent = mapToDomEvent(event.name)

    for (const targetId of targets) {
        w.push(`{`)
        w.in()
        w.push(`const __node = document.querySelector('[data-eid="${targetId}"]');`)
        w.push(`if (__node) {`)
        w.in()
        w.push(`__node.addEventListener('${domEvent}', ${handler});`)
        w.push(`__cleanups.push(() => __node.removeEventListener('${domEvent}', ${handler}));`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
    }
}

// ─── Lifecycle event registration ─────────────────────────────────────────────

function genLifecycleRegistration(
    event: EventSpecNode,
    handler: string,
    w: CodeWriter,
) {
    // Lifecycle events are dispatched as CustomEvents on window
    // by the page canvas component
    const eventName = `mava:${event.name}`
    const pageId = event.subject?.ids[0] ?? '*'

    w.push(`{`)
    w.in()
    w.push(`const __lifecycleHandler = (e) => {`)
    w.in()
    // If a specific page is targeted, only fire for that page
    if (pageId !== '*') {
        w.push(`if (e.detail?.pageId !== '${pageId}') return;`)
    }
    w.push(`${handler}(e);`)
    w.out()
    w.push(`};`)
    w.push(`window.addEventListener('${eventName}', __lifecycleHandler);`)
    w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', __lifecycleHandler));`)
    w.out()
    w.push(`}`)
}

// ─── Timeline event registration ──────────────────────────────────────────────

function genTimelineRegistration(
    event: EventSpecNode,
    handler: string,
    w: CodeWriter,
) {
    const subEvent = event.name.split('.')[1]  // start, stop, reaches, etc.
    const eventName = `mava:timeline.${subEvent}`

    if (subEvent === 'reaches') {
        // subject is time literal or variable
        const subject = event.subject?.ids[0] ?? '0'
        const isVar = !/^\d/.test(subject)   // starts with digit → literal

        w.push(`{`)
        w.in()
        if (isVar) {
            w.push(`const __target = __var['${subject}'];`)
        } else {
            w.push(`const __target = ${parseTimeToMs(subject)};`)
        }
        w.push(`const __tlHandler = (e) => {`)
        w.in()
        w.push(`if (e.detail?.positionMs >= __target) {`)
        w.in()
        w.push(`${handler}(e);`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`};`)
        w.push(`window.addEventListener('${eventName}', __tlHandler);`)
        w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', __tlHandler));`)
        w.out()
        w.push(`}`)
        return
    }

    w.push(`{`)
    w.in()
    w.push(`window.addEventListener('${eventName}', ${handler});`)
    w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', ${handler}));`)
    w.out()
    w.push(`}`)
}

// ─── Trigger body codegen ─────────────────────────────────────────────────────

function genTriggerBody(
    body: TriggerBodyNode,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    if (body.rest.type === 'ShortBody') {
        genActions(body.rest.actions, w, groups, namedTriggers)
        return
    }
    genConditionalBody(body.rest, w, groups, namedTriggers)
}

// ─── Conditional body ─────────────────────────────────────────────────────────

function genConditionalBody(
    body: ConditionalBodyNode,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    for (let i = 0; i < body.branches.length; i++) {
        const branch = body.branches[i]
        const prefix = i === 0 ? 'if' : '} else if'
        w.push(`${prefix} (${genExpr(branch.condition)}) {`)
        w.in()
        genActions(branch.actions, w, groups, namedTriggers)
        w.out()
    }

    if (body.elseBranch) {
        w.push(`} else {`)
        w.in()
        genActions(body.elseBranch.actions, w, groups, namedTriggers)
        w.out()
    }

    w.push(`}`)
}

// ─── Actions ──────────────────────────────────────────────────────────────────

function genActions(
    actions: ActionNode[],
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    for (const action of actions) {
        genAction(action, w, groups, namedTriggers)
    }
}

function genAction(
    action: ActionNode,
    w: CodeWriter,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
    namedTriggers: Record<string, string>,
) {
    switch (action.type) {

        // ── Visibility ────────────────────────────────────────────────────────
        case 'ShowAction':
        case 'HideAction': {
            const visible = action.type === 'ShowAction'
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').visible = ${visible}; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').visible = ${visible};`)
                }
            }
            break
        }

        // ── Interactive state ─────────────────────────────────────────────────
        case 'EnableAction':
        case 'DisableAction': {
            const disabled = action.type === 'DisableAction'
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').disabled = ${disabled}; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').disabled = ${disabled};`)
                }
            }
            break
        }

        // ── Highlight ─────────────────────────────────────────────────────────
        case 'HighlightAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').highlighted = true; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').highlighted = true;`)
                }
            }
            break
        }

        // ── Media ─────────────────────────────────────────────────────────────
        case 'PlayAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                const call = `document.querySelector('[data-eid="${id}"]')?.play()`
                w.push(delay
                    ? `setTimeout(() => { ${call}; }, ${parseTimeToMs(delay.raw)});`
                    : `${call};`
                )
            }
            break
        }

        case 'PauseAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) {
                w.push(`document.querySelector('[data-eid="${id}"]')?.pause();`)
            }
            break
        }

        case 'ResumeAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) {
                // media resume = play() from current position
                w.push(`document.querySelector('[data-eid="${id}"]')?.play();`)
            }
            break
        }

        case 'StopAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) {
                w.push(`{`)
                w.in()
                w.push(`const __m = document.querySelector('[data-eid="${id}"]');`)
                w.push(`if (__m) { __m.pause(); __m.currentTime = 0; }`)
                w.out()
                w.push(`}`)
            }
            break
        }

        // ── Animation ─────────────────────────────────────────────────────────
        case 'RunAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').play(); }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').play();`)
                }
            }
            break
        }

        case 'FinishAction': {
            // Force animation to its final frame by jumping to end
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) {
                w.push(`__el('${id}').finish();`)
            }
            break
        }

        // ── Navigation ────────────────────────────────────────────────────────
        case 'NavigateAction': {
            const nav = action as NavigateActionNode
            const delay = nav.delay
            const call = genNavigateCall(nav.target)
            w.push(delay
                ? `setTimeout(() => { ${call}; }, ${parseTimeToMs(delay.raw)});`
                : `${call};`
            )
            break
        }

        // ── Access control ────────────────────────────────────────────────────
        case 'LockAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) w.push(`__lock('${id}');`)
            break
        }

        case 'UnlockAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) w.push(`__unlock('${id}');`)
            break
        }

        // ── Submit ────────────────────────────────────────────────────────────
        case 'SubmitAction': {
            const ids = resolveTargetIds(action as TargetedActionNode, groups)
            for (const id of ids) {
                w.push(`document.querySelector('[data-eid="${id}"]')?.requestSubmit();`)
            }
            break
        }

        // ── Wait ──────────────────────────────────────────────────────────────
        case 'WaitAction': {
            const ms = parseTimeToMs((action as WaitActionNode).duration.raw)
            w.push(`await __waitMs(${ms});`)
            break
        }

        // ── Execute script ────────────────────────────────────────────────────
        case 'ExecuteAction': {
            const name = (action as ExecuteActionNode).scriptName
            w.push(`await __dispatch([{ type: 'script:${name}' }], { sourceNode: null, sourceId: null, event: null });`)
            break
        }

        // ── Invoke named trigger ──────────────────────────────────────────────
        case 'TriggerAction': {
            const name = (action as TriggerActionNode).triggerName
            const fnName = `__trigger_${sanitizeId(name)}`
            w.push(`await ${fnName}();`)
            break
        }

        // ── Assignment ────────────────────────────────────────────────────────
        case 'AssignAction': {
            const assign = action as AssignActionNode
            const rhs = genExpr(assign.value)
            if (assign.op === '=') {
                w.push(`__var['${assign.variable}'] = ${rhs};`)
            } else if (assign.op === '+=') {
                w.push(`__var['${assign.variable}'] += ${rhs};`)
            } else {
                w.push(`__var['${assign.variable}'] -= ${rhs};`)
            }
            break
        }
    }
}

// ─── Expression codegen ───────────────────────────────────────────────────────

function genExpr(expr: ExprNode): string {
    switch (expr.type) {
        case 'BinaryExpr': {
            const op = expr.op === 'and' ? '&&' : '||'
            return `(${genExpr(expr.left)} ${op} ${genExpr(expr.right)})`
        }
        case 'UnaryExpr':
            return `!(${genExpr(expr.operand)})`

        case 'Comparison':
            return `(${genExpr(expr.left)} ${expr.op} ${genExpr(expr.right)})`

        case 'Identifier':
            return `__var['${expr.name}']`

        case 'Literal':
            return genLiteral(expr as LiteralNode)
    }
}

function genLiteral(lit: LiteralNode): string {
    switch (lit.kind) {
        case 'string': return `"${String(lit.value).replace(/"/g, '\\"')}"`
        case 'number': return String(lit.value)
        case 'bool': return String(lit.value)
        case 'time': return String(parseTimeToMs(lit.raw))
        case 'percent': return String(lit.value)
        case 'pixels': return String(lit.value)
        case 'list': return JSON.stringify(lit.value)
        case 'object': return JSON.stringify(lit.value)
    }
}

// ─── Navigate call ────────────────────────────────────────────────────────────

function genNavigateCall(target: SubjectNode): string {
    if (target.kind === 'nav-keyword') {
        return target.ids[0] === 'next'
            ? `__page.navigateNext()`
            : `__page.navigatePrev()`
    }
    if (target.kind === 'structural-ref' && target.ref) {
        return `__navigate('${target.ref.name}')`
    }
    const id = target.ids[0] ?? ''
    return `__navigate('${id}')`
}

// ─── Target resolution ────────────────────────────────────────────────────────

function resolveTargetIds(
    action: TargetedActionNode,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
): string[] {
    const target = action.target
    if (target.kind === 'element-list') return target.ids
    if (target.kind === 'group') {
        const group = groups.get(target.ids[0])
        return group?.members ?? []
    }
    return target.ids
}

function resolveEventTargets(
    event: EventSpecNode,
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>,
): string[] {
    if (!event.subject) return []
    const subject = event.subject
    if (subject.kind === 'element-list') return subject.ids
    if (subject.kind === 'group') {
        const group = groups.get(subject.ids[0])
        return group?.members ?? []
    }
    return subject.ids
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function isLifecycleEvent(name: string): boolean {
    return [
        'mount', 'before.mount', 'unmount', 'before.unmount',
        'enter', 'leave',
    ].includes(name)
}

const DOM_EVENT_MAP: Record<string, string> = {
    'click': 'click',
    'dblclick': 'dblclick',
    'hover': 'mouseenter',
    'focus': 'focus',
    'blur': 'blur',
    'keypress': 'keypress',
    'keydown': 'keydown',
    'keyup': 'keyup',
    'submit': 'submit',
    'media.play': 'play',
    'media.pause': 'pause',
    'media.resume': 'play',
    'media.stop': 'ended',
    'media.complete': 'ended',
    'media.progress': 'timeupdate',
    'animation.start': 'animationstart',
    'animation.complete': 'animationend',
    'animation.loop': 'animationiteration',
}

function mapToDomEvent(name: string): string {
    return DOM_EVENT_MAP[name] ?? name
}

/**
 * Parse a time literal string to milliseconds.
 *   "1.5s"  → 1500
 *   "500ms" → 500
 *   "2m"    → 120000
 */
function parseTimeToMs(raw: string): number {
    if (raw.endsWith('ms')) return parseFloat(raw)
    if (raw.endsWith('m')) return parseFloat(raw) * 60_000
    if (raw.endsWith('s')) return parseFloat(raw) * 1_000
    return parseFloat(raw)
}

/**
 * Sanitize a DSL identifier to a valid JS identifier.
 * highlight_next_step → highlight_next_step  (already valid)
 * some-name           → some_name
 */
function sanitizeId(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_')
}