/**
 * codegen.ts
 *
 * Walks a validated Mava DSL AST and generates JavaScript glue code.
 * Output is a self-contained JS string that:
 *   - Registers trigger handlers into the project event system
 *   - Uses elementStore, varStore, pagesStore via injected context
 *   - Dispatches execute actions through the action registry
 *   - Wires variable.change watchers via Vue's watch()
 *
 * The generated code is NOT an ES module — it runs inside a
 * Function() scope with context injected, same as user scripts.
 *
 * Injected context shape:
 *   __el(id)        — get element proxy by id
 *   __var           — variable store proxy (project proxy)
 *   __page          — pagesStore
 *   __dispatch      — dispatchActions(actions, context)
 *   __watch(fn, cb) — Vue watch wrapper
 *   __on(event, target, handler) — register event listener on element
 *   __off(event, target, handler) — remove event listener
 *   __navigate(id)  — navigate to page
 *   __lock(id)      — lock page/section
 *   __unlock(id)    — unlock page/section
 *   __waitMs(ms)    — returns Promise that resolves after ms
 *   __namedTriggers — shared Map<name, fn> across every DSL document
 *                     activated together (see runner.ts). Named triggers are
 *                     global per mava_syntax.md §7 ("Named triggers are
 *                     global"), but each document still compiles into its
 *                     own isolated Function() scope — a bare local function
 *                     reference from one document's scope is unreachable
 *                     from another's. Routing every `trigger <name>` call
 *                     through this shared map (instead of a same-scope
 *                     function name) is what makes cross-document
 *                     invocation actually resolve.
 *
 * Every id codegen emits into `data-eid="..."` selectors, __navigate(id),
 * etc. is a real system id — but DSL source text never contains one; an
 * author only ever types the name they assigned (element name, page name,
 * lesson title). Resolving name -> id is done here via the same
 * registryResolve.ts helpers validator.ts uses, so the two can't drift on
 * what a name means.
 */

import type {
    ProgramNode,
    TriggerBodyNode, EventClauseNode, EventSpecNode,
    SubjectNode, ConditionalBodyNode,
    ExprNode, LiteralNode,
    ActionNode, TargetedActionNode,
    NavigateActionNode, WaitActionNode,
    ExecuteActionNode, TriggerActionNode,
    AssignActionNode,
} from './ast'
import type { ProjectRegistry } from './validator'
import { resolveElementIdsByName, resolvePageIdsByName, resolveLessonIdsByName, sanitizeId } from './registryResolve'

// ─── Output ───────────────────────────────────────────────────────────────────

export interface CodeGenResult {
    code: string
}

// ─── Codegen context ────────────────────────────────────────────────────────────

/**
 * Bundles everything threaded through every codegen function together —
 * `groups` (declared within this document, resolved at parse time) and
 * `registry` (project-wide name -> id lookups) — instead of adding loose
 * positional parameters one at a time as codegen's needs grow.
 */
interface CodegenCtx {
    groups: Map<string, { kind: 'element' | 'variable'; members: string[] }>
    registry: ProjectRegistry
}

// ─── Indentation helper ───────────────────────────────────────────────────────

class CodeWriter {
    private lines: string[] = []
    private indent: number = 0

    push(line: string = '') {
        this.lines.push(line
            ? `${'  '.repeat(this.indent)}${line}`
            : ''
        )
    }

    in() { this.indent++ }
    out() { this.indent = Math.max(0, this.indent - 1) }

    toString(): string {
        return this.lines.join('\n')
    }
}

// ─── Code generator ───────────────────────────────────────────────────────────

export function codegen(ast: ProgramNode, registry: ProjectRegistry): CodeGenResult {
    const w = new CodeWriter()

    // Groups are resolved at parse/validate time — we inline their members
    // directly in the generated code. Build a lookup here.
    const groups: Map<string, { kind: 'element' | 'variable'; members: string[] }> = new Map()

    for (const def of ast.body) {
        if (def.type === 'GroupDef') {
            groups.set(def.name, { kind: def.groupKind, members: def.members })
        }
    }

    const ctx: CodegenCtx = { groups, registry }

    // ── Preamble ──────────────────────────────────────────────────────────────

    w.push('// Generated by Mava DSL codegen — do not edit manually')
    w.push(`// Generated at: ${new Date().toISOString()}`)
    w.push()
    w.push('const __cleanups = [];')
    w.push()

    // ── Named trigger functions ────────────────────────────────────────────────
    // Defined first so the auto-registration pass below (and any TriggerAction
    // call from elsewhere) can reference them. Each one also registers itself
    // into the shared __namedTriggers map — see this file's header comment —
    // so `trigger <name>` calls from *any* activated document, not just this
    // one, can find and invoke it.

    for (const def of ast.body) {
        if (def.type === 'NamedTriggerDef') {
            const fnName = `__trigger_${sanitizeId(def.name)}`
            w.push(`async function ${fnName}() {`)
            w.in()
            genTriggerBody(def.body, w, ctx)
            w.out()
            w.push('}')
            w.push(`__namedTriggers.set('${def.name}', ${fnName});`)
            w.push()
        }
    }

    let triggerIndex = 0

    // ── Named trigger auto-registration ────────────────────────────────────────
    // Per mava_syntax.md's own example, a named trigger's `on <event> ...`
    // header is not decorative — it fires the trigger automatically, exactly
    // like a plain TriggerDef would, in addition to being invocable by name
    // via a `trigger <name>` action elsewhere. Route the handler through the
    // already-defined named function above instead of re-inlining the body,
    // so the two call paths can never drift out of sync with each other.
    for (const def of ast.body) {
        if (def.type === 'NamedTriggerDef') {
            triggerIndex++
            const fnName = `__trigger_${sanitizeId(def.name)}`
            w.push(`// Named trigger: ${def.name}`)
            genTriggerRegistration(def.body, triggerIndex, w, ctx, fnName)
            w.push()
        }
    }

    // ── Local triggers ────────────────────────────────────────────────────────

    for (const def of ast.body) {
        if (def.type === 'TriggerDef') {
            triggerIndex++
            w.push(`// Trigger ${triggerIndex}`)
            genTriggerRegistration(def.body, triggerIndex, w, ctx)
            w.push()
        }
    }

    // ── Cleanup export ────────────────────────────────────────────────────────

    w.push('// Return cleanup function to unregister all listeners')
    w.push('return function cleanup() {')
    w.in()
    w.push('__cleanups.forEach(fn => fn());')
    w.out()
    w.push('};')

    return { code: w.toString() }
}

// ─── Trigger registration ─────────────────────────────────────────────────────

/**
 * Generates the event listener registration for a trigger.
 * For variable.change events, uses __watch.
 * For all others, uses __on with data-eid queries.
 */
function genTriggerRegistration(
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    ctx: CodegenCtx,
    invokeName?: string,
) {
    const clause = body.eventClause

    if (clause.qualifier === 'single' || clause.qualifier === 'either') {
        // Each event independently fires the handler
        for (const event of clause.events) {
            genSingleEventRegistration(event, body, index, w, ctx, invokeName)
        }
    } else {
        // all-of — all events must fire before handler runs
        genAllOfRegistration(clause, body, index, w, ctx, invokeName)
    }
}

function genSingleEventRegistration(
    event: EventSpecNode,
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    ctx: CodegenCtx,
    invokeName?: string,
) {
    const handlerName = `__handler_${index}_${sanitizeId(event.name)}`

    w.push(`async function ${handlerName}(event) {`)
    w.in()
    if (invokeName) {
        w.push(`await ${invokeName}();`)
    } else {
        genTriggerBody(body, w, ctx)
    }
    w.out()
    w.push('}')
    w.push()

    // variable.change → Vue watcher
    if (event.name === 'variable.change') {
        const varName = event.subject?.ids[0] ?? ''
        w.push(`{`)
        w.in()
        w.push(`const stop = __watch(`)
        w.in()
        w.push(`() => __var['${varName}'],`)
        w.push(`(newVal, oldVal) => ${handlerName}({ newVal, oldVal })`)
        w.out()
        w.push(');')
        w.push(`__cleanups.push(stop);`)
        w.out()
        w.push(`}`)
        return
    }

    // timeline.* → custom timeline event
    if (event.name.startsWith('timeline.')) {
        genTimelineRegistration(event, handlerName, w)
        return
    }

    // Page lifecycle events
    if (isLifecycleEvent(event.name)) {
        genLifecycleRegistration(event, handlerName, w)
        return
    }

    // DOM events — register on each target element
    const targets = resolveEventTargets(event, ctx)
    const domEvent = mapToDomEvent(event.name)

    for (const targetId of targets) {
        w.push(`{`)
        w.in()
        w.push(`const __node = document.querySelector('[data-eid="${targetId}"]');`)
        w.push(`if (__node) {`)
        w.in()
        w.push(`__node.addEventListener('${domEvent}', ${handlerName});`)
        w.push(`__cleanups.push(() => __node.removeEventListener('${domEvent}', ${handlerName}));`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
    }
}

function genAllOfRegistration(
    clause: EventClauseNode,
    body: TriggerBodyNode,
    index: number,
    w: CodeWriter,
    ctx: CodegenCtx,
    invokeName?: string,
) {
    // Track which events have fired using a Set
    // Handler fires only when all events have been seen
    const firedSetName = `__fired_${index}`
    const totalEvents = clause.events.length

    w.push(`const ${firedSetName} = new Set();`)
    w.push()

    for (let i = 0; i < clause.events.length; i++) {
        const event = clause.events[i]
        const handlerName = `__handler_${index}_allof_${i}`

        w.push(`async function ${handlerName}(event) {`)
        w.in()
        w.push(`${firedSetName}.add(${i});`)
        w.push(`if (${firedSetName}.size === ${totalEvents}) {`)
        w.in()
        w.push(`${firedSetName}.clear();`)
        if (invokeName) {
            w.push(`await ${invokeName}();`)
        } else {
            genTriggerBody(body, w, ctx)
        }
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
        w.push()

        // Register same as single event
        genSingleEventForAllOf(event, handlerName, ctx, w)
    }
}

function genSingleEventForAllOf(
    event: EventSpecNode,
    handler: string,
    ctx: CodegenCtx,
    w: CodeWriter,
) {
    if (event.name === 'variable.change') {
        const varName = event.subject?.ids[0] ?? ''
        w.push(`{`)
        w.in()
        w.push(`const stop = __watch(() => __var['${varName}'], (nv, ov) => ${handler}({ newVal: nv, oldVal: ov }));`)
        w.push(`__cleanups.push(stop);`)
        w.out()
        w.push(`}`)
        return
    }

    if (isLifecycleEvent(event.name)) {
        genLifecycleRegistration(event, handler, w)
        return
    }

    const targets = resolveEventTargets(event, ctx)
    const domEvent = mapToDomEvent(event.name)

    for (const targetId of targets) {
        w.push(`{`)
        w.in()
        w.push(`const __node = document.querySelector('[data-eid="${targetId}"]');`)
        w.push(`if (__node) {`)
        w.in()
        w.push(`__node.addEventListener('${domEvent}', ${handler});`)
        w.push(`__cleanups.push(() => __node.removeEventListener('${domEvent}', ${handler}));`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`}`)
    }
}

// ─── Lifecycle event registration ─────────────────────────────────────────────

function genLifecycleRegistration(
    event: EventSpecNode,
    handler: string,
    w: CodeWriter,
) {
    // Lifecycle events are dispatched as CustomEvents on window
    // by the page canvas component
    const eventName = `mava:${event.name}`
    const pageId = event.subject?.ids[0] ?? '*'

    w.push(`{`)
    w.in()
    w.push(`const __lifecycleHandler = (e) => {`)
    w.in()
    // If a specific page is targeted, only fire for that page
    if (pageId !== '*') {
        w.push(`if (e.detail?.pageId !== '${pageId}') return;`)
    }
    w.push(`${handler}(e);`)
    w.out()
    w.push(`};`)
    w.push(`window.addEventListener('${eventName}', __lifecycleHandler);`)
    w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', __lifecycleHandler));`)
    w.out()
    w.push(`}`)
}

// ─── Timeline event registration ──────────────────────────────────────────────

function genTimelineRegistration(
    event: EventSpecNode,
    handler: string,
    w: CodeWriter,
) {
    const subEvent = event.name.split('.')[1]  // start, stop, reaches, etc.
    const eventName = `mava:timeline.${subEvent}`

    if (subEvent === 'reaches') {
        // subject is time literal or variable
        const subject = event.subject?.ids[0] ?? '0'
        const isVar = !/^\d/.test(subject)   // starts with digit → literal

        w.push(`{`)
        w.in()
        if (isVar) {
            w.push(`const __target = __var['${subject}'];`)
        } else {
            w.push(`const __target = ${parseTimeToMs(subject)};`)
        }
        w.push(`const __tlHandler = (e) => {`)
        w.in()
        w.push(`if (e.detail?.positionMs >= __target) {`)
        w.in()
        w.push(`${handler}(e);`)
        w.out()
        w.push(`}`)
        w.out()
        w.push(`};`)
        w.push(`window.addEventListener('${eventName}', __tlHandler);`)
        w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', __tlHandler));`)
        w.out()
        w.push(`}`)
        return
    }

    w.push(`{`)
    w.in()
    w.push(`window.addEventListener('${eventName}', ${handler});`)
    w.push(`__cleanups.push(() => window.removeEventListener('${eventName}', ${handler}));`)
    w.out()
    w.push(`}`)
}

// ─── Trigger body codegen ─────────────────────────────────────────────────────

function genTriggerBody(
    body: TriggerBodyNode,
    w: CodeWriter,
    ctx: CodegenCtx,
) {
    if (body.rest.type === 'ShortBody') {
        genActions(body.rest.actions, w, ctx)
        return
    }
    genConditionalBody(body.rest, w, ctx)
}

// ─── Conditional body ─────────────────────────────────────────────────────────

function genConditionalBody(
    body: ConditionalBodyNode,
    w: CodeWriter,
    ctx: CodegenCtx,
) {
    for (let i = 0; i < body.branches.length; i++) {
        const branch = body.branches[i]
        const prefix = i === 0 ? 'if' : '} else if'
        w.push(`${prefix} (${genExpr(branch.condition)}) {`)
        w.in()
        genActions(branch.actions, w, ctx)
        w.out()
    }

    if (body.elseBranch) {
        w.push(`} else {`)
        w.in()
        genActions(body.elseBranch.actions, w, ctx)
        w.out()
    }

    w.push(`}`)
}

// ─── Actions ──────────────────────────────────────────────────────────────────

function genActions(
    actions: ActionNode[],
    w: CodeWriter,
    ctx: CodegenCtx,
) {
    for (const action of actions) {
        genAction(action, w, ctx)
    }
}

function genAction(
    action: ActionNode,
    w: CodeWriter,
    ctx: CodegenCtx,
) {
    switch (action.type) {

        // ── Visibility ────────────────────────────────────────────────────────
        case 'ShowAction':
        case 'HideAction': {
            const visible = action.type === 'ShowAction'
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').visible = ${visible}; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').visible = ${visible};`)
                }
            }
            break
        }

        // ── Interactive state ─────────────────────────────────────────────────
        case 'EnableAction':
        case 'DisableAction': {
            const disabled = action.type === 'DisableAction'
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').disabled = ${disabled}; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').disabled = ${disabled};`)
                }
            }
            break
        }

        // ── Highlight ─────────────────────────────────────────────────────────
        case 'HighlightAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').highlighted = true; }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').highlighted = true;`)
                }
            }
            break
        }

        // ── Media ─────────────────────────────────────────────────────────────
        case 'PlayAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                const call = `document.querySelector('[data-eid="${id}"]')?.play()`
                w.push(delay
                    ? `setTimeout(() => { ${call}; }, ${parseTimeToMs(delay.raw)});`
                    : `${call};`
                )
            }
            break
        }

        case 'PauseAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) {
                w.push(`document.querySelector('[data-eid="${id}"]')?.pause();`)
            }
            break
        }

        case 'ResumeAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) {
                // media resume = play() from current position
                w.push(`document.querySelector('[data-eid="${id}"]')?.play();`)
            }
            break
        }

        case 'StopAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) {
                w.push(`{`)
                w.in()
                w.push(`const __m = document.querySelector('[data-eid="${id}"]');`)
                w.push(`if (__m) { __m.pause(); __m.currentTime = 0; }`)
                w.out()
                w.push(`}`)
            }
            break
        }

        // ── Animation ─────────────────────────────────────────────────────────
        case 'RunAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            const delay = (action as TargetedActionNode).delay
            for (const id of ids) {
                if (delay) {
                    w.push(`setTimeout(() => { __el('${id}').play(); }, ${parseTimeToMs(delay.raw)});`)
                } else {
                    w.push(`__el('${id}').play();`)
                }
            }
            break
        }

        case 'FinishAction': {
            // Force animation to its final frame by jumping to end
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) {
                w.push(`__el('${id}').finish();`)
            }
            break
        }

        // ── Navigation ────────────────────────────────────────────────────────
        case 'NavigateAction': {
            const nav = action as NavigateActionNode
            const delay = nav.delay
            const call = genNavigateCall(nav.target, ctx)
            w.push(delay
                ? `setTimeout(() => { ${call}; }, ${parseTimeToMs(delay.raw)});`
                : `${call};`
            )
            break
        }

        // ── Access control ────────────────────────────────────────────────────
        // Lock/unlock targets are pages/sections, not elements — resolved via
        // the page name map, matching validator.ts's validateTargetIsPageOrSection.
        // (__lock/__unlock are currently no-op stubs in context.ts regardless —
        // see its warnLockingUnimplemented — so this only affects what id would
        // reach them once locking is actually implemented.)
        case 'LockAction': {
            const ids = resolvePageTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) w.push(`__lock('${id}');`)
            break
        }

        case 'UnlockAction': {
            const ids = resolvePageTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) w.push(`__unlock('${id}');`)
            break
        }

        // ── Submit ────────────────────────────────────────────────────────────
        case 'SubmitAction': {
            const ids = resolveElementTargetIds(action as TargetedActionNode, ctx)
            for (const id of ids) {
                w.push(`document.querySelector('[data-eid="${id}"]')?.requestSubmit();`)
            }
            break
        }

        // ── Wait ──────────────────────────────────────────────────────────────
        case 'WaitAction': {
            const ms = parseTimeToMs((action as WaitActionNode).duration.raw)
            w.push(`await __waitMs(${ms});`)
            break
        }

        // ── Execute script ────────────────────────────────────────────────────
        case 'ExecuteAction': {
            const name = (action as ExecuteActionNode).scriptName
            w.push(`await __dispatch([{ type: 'script:${name}' }], { sourceNode: null, sourceId: null, event: null });`)
            break
        }

        // ── Invoke named trigger ──────────────────────────────────────────────
        // Looked up on the shared __namedTriggers map, not a bare local
        // function name — the target may be declared in a different DSL
        // document than this one (named triggers are global, see this
        // file's header comment). `?.()` is a deliberate no-op rather than
        // a ReferenceError if the name isn't found — validator.ts's
        // TriggerAction check is what's supposed to catch a genuinely
        // missing name before this ever runs.
        case 'TriggerAction': {
            const name = (action as TriggerActionNode).triggerName
            w.push(`await __namedTriggers.get('${name}')?.();`)
            break
        }

        // ── Assignment ────────────────────────────────────────────────────────
        case 'AssignAction': {
            const assign = action as AssignActionNode
            const rhs = genExpr(assign.value)
            if (assign.op === '=') {
                w.push(`__var['${assign.variable}'] = ${rhs};`)
            } else if (assign.op === '+=') {
                w.push(`__var['${assign.variable}'] += ${rhs};`)
            } else {
                w.push(`__var['${assign.variable}'] -= ${rhs};`)
            }
            break
        }
    }
}

// ─── Expression codegen ───────────────────────────────────────────────────────

function genExpr(expr: ExprNode): string {
    switch (expr.type) {
        case 'BinaryExpr': {
            const op = expr.op === 'and' ? '&&' : '||'
            return `(${genExpr(expr.left)} ${op} ${genExpr(expr.right)})`
        }
        case 'UnaryExpr':
            return `!(${genExpr(expr.operand)})`

        case 'Comparison':
            return `(${genExpr(expr.left)} ${expr.op} ${genExpr(expr.right)})`

        case 'Identifier':
            return `__var['${expr.name}']`

        case 'Literal':
            return genLiteral(expr as LiteralNode)
    }
}

function genLiteral(lit: LiteralNode): string {
    switch (lit.kind) {
        case 'string': return `"${String(lit.value).replace(/"/g, '\\"')}"`
        case 'number': return String(lit.value)
        case 'bool': return String(lit.value)
        case 'time': return String(parseTimeToMs(lit.raw))
        case 'percent': return String(lit.value)
        case 'pixels': return String(lit.value)
        case 'list': return JSON.stringify(lit.value)
        case 'object': return JSON.stringify(lit.value)
    }
}

// ─── Navigate call ────────────────────────────────────────────────────────────

function genNavigateCall(target: SubjectNode, ctx: CodegenCtx): string {
    if (target.kind === 'nav-keyword') {
        return target.ids[0] === 'next'
            ? `__page.navigateNext()`
            : `__page.navigatePrev()`
    }
    if (target.kind === 'structural-ref' && target.ref) {
        const { refType, name } = target.ref
        if (refType === 'l') {
            // No standalone "navigate to a lesson" operation exists anywhere
            // in this app (pages.loadPage only knows page ids) — the closest
            // well-defined behavior is entering the lesson's first page by
            // `order`. Documented interpretation, not a spec-mandated one.
            const lessonIds = resolveLessonIdsByName(name, ctx.registry)
            const firstPageId = lessonIds.length ? ctx.registry.lessonFirstPageId[lessonIds[0]] : undefined
            return `__navigate('${firstPageId ?? name}')`
        }
        const pageIds = resolvePageIdsByName(name, ctx.registry)
        return `__navigate('${pageIds[0] ?? name}')`
    }
    const name = target.ids[0] ?? ''
    const pageIds = resolvePageIdsByName(name, ctx.registry)
    return `__navigate('${pageIds[0] ?? name}')`
}

// ─── Target resolution ────────────────────────────────────────────────────────

/**
 * Resolves a bracket-list/group target's raw author-typed names to real
 * element ids. A name matching multiple elements expands to all of them
 * (mirrors validator.ts's resolveTargetIds — the same ambiguity there is
 * already surfaced as a W008 warning at validate time, so codegen just acts
 * on it rather than re-diagnosing). A name matching nothing passes through
 * unchanged — validation is expected to have already rejected that case;
 * this is only a fallback so codegen never throws on its own.
 */
function resolveElementTargetIds(action: TargetedActionNode, ctx: CodegenCtx): string[] {
    return resolveNamesToElementIds(rawTargetNames(action.target, ctx), ctx)
}

function resolveEventTargets(event: EventSpecNode, ctx: CodegenCtx): string[] {
    if (!event.subject) return []
    return resolveNamesToElementIds(rawSubjectNames(event.subject, ctx), ctx)
}

function rawTargetNames(target: SubjectNode, ctx: CodegenCtx): string[] {
    if (target.kind === 'element-list') return target.ids
    if (target.kind === 'group') {
        const group = ctx.groups.get(target.ids[0])
        return group?.members ?? []
    }
    return target.ids
}

function rawSubjectNames(subject: SubjectNode, ctx: CodegenCtx): string[] {
    if (subject.kind === 'element-list') return subject.ids
    if (subject.kind === 'group') {
        const group = ctx.groups.get(subject.ids[0])
        return group?.members ?? []
    }
    return subject.ids
}

function resolveNamesToElementIds(names: string[], ctx: CodegenCtx): string[] {
    return names.flatMap(name => {
        const matches = resolveElementIdsByName(name, ctx.registry)
        return matches.length > 0 ? matches : [name]
    })
}

/** Page/section targets for lock/unlock — see the LockAction/UnlockAction comment above. */
function resolvePageTargetIds(action: TargetedActionNode, ctx: CodegenCtx): string[] {
    const target = action.target
    if (target.kind !== 'element-list') return []
    return target.ids.map(name => {
        const matches = resolvePageIdsByName(name, ctx.registry)
        return matches[0] ?? name
    })
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function isLifecycleEvent(name: string): boolean {
    return [
        'mount', 'before.mount', 'unmount', 'before.unmount',
        'enter', 'leave',
    ].includes(name)
}

const DOM_EVENT_MAP: Record<string, string> = {
    'click': 'click',
    'dblclick': 'dblclick',
    'hover': 'mouseenter',
    'focus': 'focus',
    'blur': 'blur',
    'keypress': 'keypress',
    'keydown': 'keydown',
    'keyup': 'keyup',
    'submit': 'submit',
    'form.submit': 'submit',
    'form.reset': 'reset',
    'media.play': 'play',
    'media.pause': 'pause',
    'media.resume': 'play',
    'media.stop': 'ended',
    'media.complete': 'ended',
    'media.progress': 'timeupdate',
    'animation.start': 'animationstart',
    'animation.complete': 'animationend',
    'animation.loop': 'animationiteration',
}

function mapToDomEvent(name: string): string {
    return DOM_EVENT_MAP[name] ?? name
}

/**
 * Parse a time literal string to milliseconds.
 *   "1.5s"  → 1500
 *   "500ms" → 500
 *   "2m"    → 120000
 */
function parseTimeToMs(raw: string): number {
    if (raw.endsWith('ms')) return parseFloat(raw)
    if (raw.endsWith('m')) return parseFloat(raw) * 60_000
    if (raw.endsWith('s')) return parseFloat(raw) * 1_000
    return parseFloat(raw)
}

